### ISSUE TITLE
Generate *.obt Archive is disfunctional

### ISSUE THREAD

**Issue by HymiR** [lxqt/obconf-qt#14]
No matter which folder or file of an openbox3 theme is selected - the error is everytime the same:

> "/path/to/folder/or/file/of/any/type/makes/no/difference" does not
> seem to be a correct theme directory

**Comment by pmattern** [comment]
Confirmed.

Looks like ObConf-Qt was simply using the dialog to *install* themes here:
If `Create a theme archive [...]` is invoked in ObConf it expects a theme folder like `/usr/share/themes/Clearloks` and upon selection creates an archive `~/<theme>.obt`. It could be discussed whether selecting the archive's path shouldn't be possible but other than that it's plausible behaviour.
Unlike this ObConf-Qt expects an `*.obt` archive when the very same button is clicked which doesn't seem exactly reasonable to me.

**Comment by HymiR** [comment]
I think a user expects both should work:
selecting
- /usr/share/themnes/mythemefolder
- ~/mythemefolder

Currently I don't have time to hack around because of my bachelor thesis.
Is currently anyone involved fixing this?
I think I have time to solve this next month...

**Comment by pmattern** [comment]
As for the pace this issue is dealt with we aren't suffering from too many devs participating... So good patches are always welcome. Also, note that ObConf-Qt probably isn't one of the components most prioritized: while Openbox is the recommended window manager for now its future as such is all but certain as it'll never support Wayland.

The counterpart of theme directories `/usr/share/themes/foo` is `~/.local/share/themes/bar`, not `~/bar`. But as stated above personally I think the theme directory to get packed should be arbitrary, maybe with the above directories as default. Why shouldn't it be allowed to pack e. g. a test theme that's outside of the usual paths e. g. to hand it to someone else?

**Comment by jsm222** [comment]
I'm looking into it, the matter seems to be that the dialog is not a folder/dir but a file. The point is to be able to create an obt from an existing theme folder. ..any dir with openbox-3/themerc seem to be allowed. I'll keep you informed
